/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"

#include "tflite-model/tflite_learn_6.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"

const char* ei_classifier_inferencing_categories[] = { "value" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_5_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45 };
const uint32_t ei_dsp_config_5_axes_size = 46;
ei_dsp_config_raw_t ei_dsp_config_5 = {
    5, // uint32_t blockId
    1, // int implementationVersion
    46, // int length of axes
    1.0f // float scale-axes
};

const uint8_t ei_dsp_blocks_size = 1;
ei_model_dsp_t ei_dsp_blocks[ei_dsp_blocks_size] = {
    { // DSP block 5
        5,
        46, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_5, // pointer to config struct
        ei_dsp_config_5_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_5_axes_size, // number of axes
        1, // version
        nullptr, // factory function
    }
};
const ei_config_tflite_graph_t ei_config_tflite_graph_6 = {
    .implementation_version = 1,
    .model = tflite_learn_6,
    .model_size = tflite_learn_6_len,
    .arena_size = tflite_learn_6_arena_size
};

ei_learning_block_config_tflite_graph_t ei_learning_block_config_6 = {
    .implementation_version = 1,
    .classification_mode = EI_CLASSIFIER_CLASSIFICATION_MODE_REGRESSION,
    .block_id = 6,
    .object_detection = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .output_data_tensor = 0,
    .output_labels_tensor = 1,
    .output_score_tensor = 2,
    .threshold = 0,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_tflite_graph_6
};

const uint8_t ei_learning_blocks_size = 1;
const uint32_t ei_learning_block_6_inputs[1] = { 5 };
const uint8_t ei_learning_block_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks[ei_learning_blocks_size] = {
    {
        6,
        false,
        &run_nn_inference,
        (void*)&ei_learning_block_config_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_6_inputs,
        ei_learning_block_6_inputs_size,
        1
    },
};


const ei_object_detection_nms_config_t ei_object_detection_nms = {
    0.0f, /* NMS confidence threshold */
    0.2f  /* NMS IOU threshold */
};

const ei_impulse_t impulse_620515_0 = {
    .project_id = 620515,
    .project_owner = "Telly R",
    .project_name = "IDS",
    .impulse_id = 2,
    .impulse_name = "Impulse #2",
    .deploy_version = 3,

    .nn_input_frame_size = 46,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 46,
    .dsp_input_frame_size = 1 * 46,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,
    .dsp_blocks_size = ei_dsp_blocks_size,
    .dsp_blocks = ei_dsp_blocks,
    
    .object_detection_count = 0,
    .fomo_output_size = 0,

    
    .visual_ad_grid_size_x = 0,
    .visual_ad_grid_size_y = 0,
    
    .tflite_output_features_count = 1,
    .learning_blocks_size = ei_learning_blocks_size,
    .learning_blocks = ei_learning_blocks,

    .postprocessing_blocks_size = 0,
    .postprocessing_blocks = nullptr,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "axis0 + axis1 + axis2 + axis3 + axis4 + axis5 + axis6 + axis7 + axis8 + axis9 + axis10 + axis11 + axis12 + axis13 + axis14 + axis15 + axis16 + axis17 + axis18 + axis19 + axis20 + axis21 + axis22 + axis23 + axis24 + axis25 + axis26 + axis27 + axis28 + axis29 + axis30 + axis31 + axis32 + axis33 + axis34 + axis35 + axis36 + axis37 + axis38 + axis39 + axis40 + axis41 + axis42 + axis43 + axis44 + axis45",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories,
    .object_detection_nms = ei_object_detection_nms
};

ei_impulse_handle_t impulse_handle_620515_0 = ei_impulse_handle_t( &impulse_620515_0 );
ei_impulse_handle_t& ei_default_impulse = impulse_handle_620515_0;

#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
